frontend:
    image: node:13
    working_dir: /var/app/frontend
    ports:
      - 3000:3000
    command: yarn start
    stdin_open: true
    volumes:
      - ./:/var/app/frontend
      - ./node_modules:/var/app/frontend/node_modules

