version: "3.7"
services:
  db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=bookup-db
      - MYSQL_USER=bookup-user
      - MYSQL_PASSWORD=123456789
    ports:
      - "3306:3306"

  backend:
    image: node:13
    working_dir: /var/app/backend
    ports:
      - 4000:4000
      - 9229:9229
    command: >
      sh -c "npm i bcrypt &&
             npm i @types/bcrypt &&
             npm run typeorm schema:sync &&
             npm run dev"
    volumes:
      - ../bookup-backend:/var/app/backend

  frontend:
    image: node:13
    working_dir: /var/app/frontend
    ports:
      - 3000:3000
    command: yarn start
    stdin_open: true
    volumes:
      - ./:/var/app/frontend
      - ./node_modules:/var/app/frontend/node_modules

